// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXo1jHv2R1pjS1iLN95uT6KCszas7VmA',
    appId: '1:1003624786726:web:30bbff5ccd6bc9560fefe7',
    messagingSenderId: '1003624786726',
    projectId: 'chat-app-6d3e5',
    authDomain: 'chat-app-6d3e5.firebaseapp.com',
    storageBucket: 'chat-app-6d3e5.appspot.com',
    measurementId: 'G-YNT5RTPR8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQAhrVpS4Igp0WXjEeyz0WPm_rdzmdWI',
    appId: '1:1003624786726:android:d26d9ccf4bb3fd730fefe7',
    messagingSenderId: '1003624786726',
    projectId: 'chat-app-6d3e5',
    storageBucket: 'chat-app-6d3e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHH-YfdGR8OfOQCgqqwAKKexhKQNeI4n8',
    appId: '1:1003624786726:ios:e4f5ba0ad2410bb00fefe7',
    messagingSenderId: '1003624786726',
    projectId: 'chat-app-6d3e5',
    storageBucket: 'chat-app-6d3e5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
